server:
  port: 8081

spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册

logging:
  level:
    org.springframework.cloud.gateway: debug