server:
  port: 8889

spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: true
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true #使用ip地址注册
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12

logging:
  level:
    org.springframework.cloud.gateway: debug