eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true #使用ip地址注册
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
server:
  port: 8766
spring:
  application:
    name: facial_recognision
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/campusecurity?serverTimezone=GMT&useSSL=false
    username: root
    password: Gehanchen260817
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    host: 192.168.0.103
    port: 5672
    username: admin
    password: 123456
campusecurity:
  face:
    apiKey: 91GjPmdZWv55Yyueh9znGNk6
    secretKey: 3lfhI7s22mSAMPROvztuHDtbgb7moOKs
    appId: 24064772
    groupIdList: ghc
