eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: userservice
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
