eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: userservice
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/campusecurity?serverTimezone=GMT&useSSL=false
    username: root
    password: Gehanchen260817
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
debug: true